### ISSUE TITLE
bootpartition.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by kubden** [remahl/meta-cubie-ds#1]
Hi,
As a rookie, I find the process  Yocto/Openembedded a little unclear.
I cloned meta-sunxi.git and meta-cubie-ds.git, i created the project build-CUBIEBOARD3 directory instead  cubietruck directory. 
However, i downloaded the files from this repository (cubietruck).
I use Hob application to build the image and I selected the "machine cubietruck" and the "image core-image-minimal-installer".
An error has occured during the execution and the building image!
Could you make a suggestion to help resolve this difficulty below?
Thank in advance.
Denis

DEBUG: Executing shell function do_install
install: cannot stat '/home/voxit/poky/build-CUBIEBOARD3/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/truckinstall/0.1-r0/bootpartition.tar.gz': No such file or directory
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_install (log file is located at /home/voxit/poky/build-CUBIEBOARD3/tmp/work/armv7a-vfp-neon-poky-linux-gnueabi/truckinstall/0.1-r0/temp/log.do_install.22403)

**Comment by remahl** [comment]
Hello,
Just modified the recipe. The bootpartition.tar.gz was part of the recipe. 
This is a rather bad idea, since we have to tweak some stuff, so that the bitbake could handle the data. (which was not done...)
A better solution is to store the data in a git repository and modify the recipe, so that the data is fetched from the repository. (see recipes-extended/truckinstall/truckinstall_0.1.bb)

Hope this helps.

**Comment by kubden** [comment]
As i said in my previous message, i am learning to use Yocto/OpenEmbedded and i would just like to build an image which should boot on sdcard. Please let me know how to debug your first application, 
because I still do not understand the mechanisms of the recipes with bitbake. 
I have a book about Yocto and I want to study it.
Thanks.
